# Generated by Django 5.0.3 on 2024-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('stuno', models.CharField(max_length=12)),
                ('cno', models.CharField(max_length=3)),
                ('grade', models.SmallIntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('stuno', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=3)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
