# Generated by Django 5.0.3 on 2024-04-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_student_birthdate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scores',
            unique_together={('stuno', 'cno')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('stuno', 'name')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['sex'], name='sex'),
        ),
        migrations.AlterModelTable(
            name='scores',
            table='scores',
        ),
    ]
