# Generated by Django 5.0.3 on 2024-04-09 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_scores_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stus3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.stus3')),
            ],
        ),
    ]
